### ISSUE TITLE
@ not possible intro from keyboard 

### ISSUE THREAD

**Issue by flyingsinver** [thekirankumar/youtube-android-auto#81] opened 2018-02-12 09:05 UTC
Hello 

I can't intro @ from keyboard in web search CarStream app.

Please, can you implement it ?

From Spain,
Thank you very much 
Very good job !!!

Best regards,
Chema

**Comment by thekirankumar** [comment] 2018-02-12 09:13
Duplicate of #22 
Will be added but requires a lot of work. Taking up next after bookmark settings
In the meantime, use the phone carstream app to login once.

**Closed by thekirankumar** 2018-02-12 09:13 UTC
Labels: duplicate
